name: Create badge

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */12 * * *"

jobs:
  crate_badge:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Git and create PR
        run: |
          git config --global user.name "Mayank Chaudhari<https://mayank-chaudhari.vercel.app>"
          git config --global user.email "mayank.srmu@gmail.com"
          git fetch
          git checkout main
      - name: Set up repo
        run: chmod +x ./npm-downloads.sh && (sudo bash ./npm-downloads.sh || ./npm-downloads.sh)
      - name: Push changes back to repo
        continue-on-error: true
        run: |
          git add .
          git commit -m 'Update npm download badge [skip ci]'
          git push origin main
